[package]
name = "ssdp"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[dependencies]
romio = "0.3.0-alpha.8"
futures-preview = "0.3.0-alpha.16"
futures-timer = "0.2.0"
httparse = "1.3.3"

[dev-dependencies]
runtime = "0.3.0-alpha.4"
runtime-tokio = "0.3.0-alpha.4"
hyper = "0.12.29"
failure = "0.1.5"
