[package]
name = "ssdp-client"
version = "0.4.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
description = "An asynchronous library for discovering, notifying and subscribing to devices and services on a network."
categories = ["network-programming", "asynchronous"]
keywords = ["async", "ssdp", "networking", "protocols"]
repository = "https://github.com/jjakobh/ssdp-client"
documentation = "https://docs.rs/ssdp-client"
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
travis-ci = { repository = "jjakobh/ssdp-client", branch = "master" }

[dependencies]
romio = "0.3.0-alpha.9"
futures-timer = "0.3"
log = "0.4"
futures-preview = "0.3.0-alpha.18"
futures-async-stream = "0.1.0-alpha.5"
err-derive = "0.1.6"

[dev-dependencies]
runtime = "0.3.0-alpha.7"
