[package]
name = "ssdp-client"
version = "0.2.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[dependencies]
romio = "0.3.0-alpha.9"
futures-preview = "0.3.0-alpha.17"
futures-timer = "0.2"

[dev-dependencies]
runtime = "0.3.0-alpha.6"
