[package]
name = "ssdp-client"
version = "0.3.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
description = "An asynchronous library for discovering, notifying and subscribing to devices and services on a network."
categories = ["Asynchronous", "Network Programming"]
keywords = ["async", "ssdp", "networking", "protocols"]
repository = "https://github.com/jjakobh/ssdp-client"
documentation = "https://docs.rs/ssdp-client"
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
travis-ci = { repository = "jjakobh/ssdp-client", branch = "master" }
maintainance = { status = "active" }

[dependencies]
romio = "0.3.0-alpha.9"
futures-preview = "0.3.0-alpha.17"
futures-timer = "0.2"
display_attr = "0.1.1"

[dev-dependencies]
runtime = "0.3.0-alpha.6"
